### ISSUE TITLE
Questions about choice of tags

### ISSUE THREAD

**Issue by zyddnys** [fpgaminer/joytag#2]
I see you have `commission` and `skeb_commission` in your tag list. It feels odd to me how you can know if a drawing is a commission by just looking at it.

**Comment by fpgaminer** [comment]
Thank you!  Yeah, the tag blacklist used while building the training set for this model is compiled by hand so some things like that slip through.  Thank you for pointing those out, I'll add them to the blacklist and things will get updated during the next training run.

The blacklist is maintained here for now: https://github.com/fpgaminer/danbooru-metadata/blob/main/tag_blacklist.txt
Your suggestion and a few others will go up soon.

That said ... the model does surprisingly well predicting commission anyway for some reason...

```
Tag: commission (526) (cnt: 34958)
Precision: 0.3581
Recall: 0.2721
F1: 0.3092
TP: 77, TN: 32347, FP: 138, FN: 206
```
