### ISSUE TITLE
Great work. Will you release finetune code?

### ISSUE THREAD

**Issue by LianghuiGuo** [fpgaminer/joytag#7]
Do you have plans to release code for finetuning?

**Comment by fpgaminer** [comment]
Thank you. I'll try to get my training code cleaned up and released when I have a chance.

**Comment by hussamsh** [comment]
I would also be interested in some instruction about how to finetune this model and how to add more tags to top_tags.txt.

**Comment by fpgaminer** [comment]
Training code has been added: https://github.com/fpgaminer/joytag/tree/main/training

The training script supports a `finetune-path` argument so it can load a pretrained checkpoint. All the dataset processing scripts are in `fused-dataset` folder.

So for finetuning, I'd just get the data into the right format based on the data processing scripts, and then the training script with a `finetune-path` argument should do the trick.

As for adding tags for a finetune run, you'd probably need to modify the code slightly to resize the pretrained model's head.
